### ISSUE TITLE
Animações de Ordem

### ISSUE THREAD

**Issue by SergioMacellani** [buff-buff-studio/Between-Death#12]
# Descrição
## Todas as animações base de ordem:

- Andar
- Correr
- Idle
- Pulo
- Dash
- Ataques 4x

# Referencias
### [Ataques - Jogo](https://www.youtube.com/watch?v=uj80RSvV0TE&ab_channel=BaderAlqahtani)

# Tasks

- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #19
- [x] #20
- [x] #21
- [x] #22

**Comment by RenzoDiniz** [comment]
@Bozzipontojpg 
## [Referências de ataques e poses](https://youtu.be/5PfXnlzyBcs?t=346)

**Comment by Bozzipontojpg** [comment]
@UrsoTheLobster 
## [Ideias de Referencias](https://www.youtube.com/watch?v=_xzy4Lem6os&list=PLFwXBg9A5g_Tmox8LYyERhtWlEw8UrpBh&index=1&t=1705s&ab_channel=LivingAnachronism)
