### ISSUE TITLE
Menu de Passivas - Prototipagem

### ISSUE THREAD

**Issue by SergioMacellani** [buff-buff-studio/Between-Death#130]

**Comment by Jubabibou** [comment]
![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/299bf35c-a277-44f8-8236-f72cc13b0e41)
![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/dbd2f286-4e8c-4e53-8c2d-54c29b452d0f)
