### ISSUE TITLE
Level Cidade - Janela/Vitral (UV)

### ISSUE THREAD

**Issue by SergioMacellani** [buff-buff-studio/Between-Death#138]

**Comment by Jubabibou** [comment]
![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/4c65367d-f06f-4119-b397-7f1cc79f3019)



![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/77c548cc-173a-4b1b-b65f-cbe640e7dc1e)
