### ISSUE TITLE
Level Coliseu - Suporte do Sino (Modelo)

### ISSUE THREAD

**Issue by SergioMacellani** [buff-buff-studio/Between-Death#213]
![image](https://github.com/buff-buff-studio/Between-Death/assets/54212586/8e3c224d-694c-4865-a9e5-59a5c2431504)
Vigas de madeira circulares sustentadas pelas Vigas #214  (topo onde prende a corrente fechado para poder "erguer o sino" pela unity, clipando sobre o topo e escondendo as correntes)

**Comment by Jubabibou** [comment]
![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/6b80ed8f-4cc8-467b-a6ac-99c4467d2d06)
