### ISSUE TITLE
Level Coliseu - Vigas (Modelo)

### ISSUE THREAD

**Issue by SergioMacellani** [buff-buff-studio/Between-Death#214]
![image](https://github.com/buff-buff-studio/Between-Death/assets/54212586/3b1d592d-d383-4995-a801-26722807e14d)
![image](https://github.com/buff-buff-studio/Between-Death/assets/54212586/3494621d-8665-4395-b61d-d8855bbcb923)
Vigas para sustentar Suporte do Sino #213 Referencia de silhueta na primeira imagem (no geral, sem os cascos de pedra) e de arquitetura na segunda

**Comment by Jubabibou** [comment]
![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/4440861d-5905-42fd-8957-25ce7705b38b)
