### ISSUE TITLE
Level Coliseu - Muralha (Modelo)

### ISSUE THREAD

**Issue by SergioMacellani** [buff-buff-studio/Between-Death#222]

**Comment by Jubabibou** [comment]
![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/9269c966-b3e9-487c-a373-ac538e8d7fb7)



![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/bf5c5f9e-b17b-491d-9c88-360c0549a1c3)



![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/efb98567-5a41-4be9-a2c1-81b258750a69)
