### ISSUE TITLE
Pop-Up de Upgrade - Prototipagem

### ISSUE THREAD

**Issue by SergioMacellani** [buff-buff-studio/Between-Death#272]
## Descrição
Ao abrir um baú um popup vai aparecer com 3 opções de upgrade, Vida, Força e Velocidade.

> [!NOTE]
> Preferencia por ser uma seleção em pilares e não colunas

## Referencias

![Image](https://github.com/buff-buff-studio/Between-Death/assets/17664054/bf4141bf-69c5-40d0-82fe-cca053476fec)

![Image](https://github.com/buff-buff-studio/Between-Death/assets/17664054/cd62802b-1de8-4aae-875d-41e54c0347be)

**Comment by Jubabibou** [comment]
![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/b2d5a738-b17e-40e6-99e9-f9ee6428aef0)
