### ISSUE TITLE
Pop-Up de Baú - Prototipagem

### ISSUE THREAD

**Issue by SergioMacellani** [buff-buff-studio/Between-Death#275]
## Descrição
Ao abrir um baú um popup vai aparecer com a descrição do que você encontrou, pode ser um documento ou uma skill

> [!NOTE]
> - Deve aparecer um botão para abrir o Menu e ver o item que recebeu,
> - Localizado na Lateral ou no Centro

## Referencias

![Image](https://github.com/buff-buff-studio/Between-Death/assets/17664054/0c134d94-ca66-4371-ab05-d89f43fd7dc6)

**Comment by Jubabibou** [comment]
![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/3d1de0c7-cf17-4f27-b020-4f3c86d554a9)
