### ISSUE TITLE
Level Coliseu - Fogueira (Modelo)

### ISSUE THREAD

**Issue by SergioMacellani** [buff-buff-studio/Between-Death#304]

**Comment by Jubabibou** [comment]
![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/35cdb649-dba1-4ee8-8bc5-642fb1f996cc)

**Comment by Jubabibou** [comment]
![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/eefc7a7c-dfc0-4e10-8782-822c456589f3)


Esse asset ta no arquivo assetsbetweendeath
