### ISSUE TITLE
Preparação do Rig - Assustado

### ISSUE THREAD

**Issue by SergioMacellani** [buff-buff-studio/Between-Death#61]

**Comment by LucasQuinino** [comment]
@UrsoTheLobster preciso que voce mande os seus personagens no drive

**Comment by RenzoDiniz** [comment]
@LucasQuinino https://drive.google.com/drive/folders/1sH0dvaQpIjhxyOZG7nmItylJnjHP5ix9
se não tiver acesso por algum motivo, ta na pasta Personagens no drive to TI
