### ISSUE TITLE
Level Cidade - Janela/Vitral (Modelo)

### ISSUE THREAD

**Issue by SergioMacellani** [buff-buff-studio/Between-Death#89]

**Comment by Jubabibou** [comment]
Fiz duas variações de Janela (pequena e curva VS grande e triangular, aí da pra variar)


![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/b01f197b-e3f6-43ba-acdf-1bcafe70abd8)



![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/b8ab1636-1cdb-41a8-956e-7e588c7ac09d)




![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/906534ac-0ae3-42de-9608-b6bfab952fef)
