### ISSUE TITLE
Level Cidade - Porta (Modelo)

### ISSUE THREAD

**Issue by SergioMacellani** [buff-buff-studio/Between-Death#91]

**Comment by Jubabibou** [comment]
![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/b2c5527d-27af-42a7-8752-fb0846ec8225)


Renzo vai fazer a porta porta, fiz a moldura

**Comment by Jubabibou** [comment]
![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/dc6b1172-b41b-4fa2-8dde-1a86e30f85e3)

**Comment by Jubabibou** [comment]
![Image](https://github.com/buff-buff-studio/Between-Death/assets/69398641/e3d1abcd-820f-49ec-aadf-0d7c32dfe632)
